ARG BASE_IMAGE=positronic-base:latest
FROM ${BASE_IMAGE}

# Set working directory
WORKDIR /positronic


# Copy source code into the image
COPY . .


# Set Python path
ENV PYTHONPATH=/positronic

# Default command
CMD ["bash"]
